spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/grad_step'
    password: 'join-town'
    username: 'root'
  flyway:
    enabled: true
    locations: "classpath:db/migration"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect